[PoC RESULT]: False
[PoC MSG]:
============================== Run PoC ==============================
------------------------------ Standard Output ------------------------------
[0m[38;5;245mrunning 1 test from ./webfinger/lookup.test.ts[0m
lookupWebFinger() ...
  invalid resource ... [0m[32mok[0m [0m[38;5;245m(1ms)[0m
  connection refused ... [0m[32mok[0m [0m[38;5;245m(4ms)[0m
  not found ... [0m[32mok[0m [0m[38;5;245m(3ms)[0m
  acct ... [0m[32mok[0m [0m[38;5;245m(1ms)[0m
  https ... [0m[32mok[0m [0m[38;5;245m(1ms)[0m
  invalid response ... [0m[32mok[0m [0m[38;5;245m(2ms)[0m
  redirection ... [0m[32mok[0m [0m[38;5;245m(2ms)[0m
  infinite redirection ... [0m[32mok[0m [0m[38;5;245m(5ms)[0m
  redirection to different protocol ... [0m[32mok[0m [0m[38;5;245m(1ms)[0m
  redirection to private address ... [0m[31mFAILED[0m [0m[38;5;245m(3ms)[0m
lookupWebFinger() ... [0m[31mFAILED[0m (due to 1 failed step) [0m[38;5;245m(26ms)[0m

[0m[1m[37m[41m ERRORS [0m

lookupWebFinger() ... redirection to private address [0m[38;5;245m=> ./webfinger/lookup.test.ts:135:11[0m
[0m[1m[31merror[0m: AssertionError: Expected function to reject.
    throw new AssertionError(
[0m[31m          ^[0m
    at [0m[1m[3massertRejects[0m ([0m[36mhttps://jsr.io/@std/assert/0.226.0/assert_rejects.ts[0m:[0m[33m119[0m:[0m[33m11[0m)
    at async [0m[36mfile:///workspace/fedify/src/webfinger/lookup.test.ts[0m:[0m[33m136[0m:[0m[33m5[0m
    at async [0m[1m[3minnerWrapped[0m ([0m[36mext:cli/40_test.js[0m:[0m[33m180[0m:[0m[33m5[0m)
    at async [0m[1m[3mexitSanitizer[0m ([0m[36mext:cli/40_test.js[0m:[0m[33m96[0m:[0m[33m27[0m)
    at async [0m[1m[3mObject.outerWrapped [as fn][0m ([0m[36mext:cli/40_test.js[0m:[0m[33m123[0m:[0m[33m14[0m)
    at async [0m[1m[3mTestContext.step[0m ([0m[36mext:cli/40_test.js[0m:[0m[33m481[0m:[0m[33m22[0m)
    at async [0m[36mfile:///workspace/fedify/src/webfinger/lookup.test.ts[0m:[0m[33m135[0m:[0m[33m3[0m
    at async [0m[1m[3mfn[0m ([0m[36mfile:///workspace/fedify/src/testing/mod.ts[0m:[0m[33m59[0m:[0m[33m9[0m)

[0m[1m[37m[41m FAILURES [0m

lookupWebFinger() ... redirection to private address [0m[38;5;245m=> ./webfinger/lookup.test.ts:135:11[0m

[0m[31mFAILED[0m | 0 passed (9 steps) | 1 failed (1 step) [0m[38;5;245m(34ms)[0m


------------------------------ Standard Error ------------------------------
[0m[32mCheck[0m file:///workspace/fedify/src/webfinger/lookup.test.ts
[0m[1m[31merror[0m: Test failed

------------------------------ Finish Evaluation ------------------------------


[UnitTest RESULT]: None
[UnitTest MSG]:
 None

[Validation TYPE]: validation_fail