[PoC RESULT]: False
[PoC MSG]:
============================== Run PoC ==============================
------------------------------ Standard Output ------------------------------
============================= test session starts ==============================
platform linux -- Python 3.8.20, pytest-8.3.5, pluggy-1.5.0
rootdir: /workspace/rdiffweb
configfile: pyproject.toml
collected 0 items / 1 error

==================================== ERRORS ====================================
___________ ERROR collecting rdiffweb/core/model/tests/test_user.py ____________
<frozen importlib._bootstrap_external>:843: in exec_module
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
rdiffweb/core/model/__init__.py:27: in <module>
    from ._sshkey import SshKey  # noqa
rdiffweb/core/model/_sshkey.py:24: in <module>
    class SshKey(Base):
rdiffweb/core/model/_sshkey.py:27: in SshKey
    UniqueConstraint('UserID', 'Key', name='_user_key_uc'),
E   NameError: name 'UniqueConstraint' is not defined
=========================== short test summary info ============================
ERROR rdiffweb/core/model/tests/test_user.py - NameError: name 'UniqueConstra...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 0.57s ==========================

------------------------------ Finish Evaluation ------------------------------


[UnitTest RESULT]: None
[UnitTest MSG]:
 None

[Validation TYPE]: validation_fail