[PoC RESULT]: False
[PoC MSG]:
============================== Run PoC ==============================
------------------------------ Standard Output ------------------------------
============================= test session starts ==============================
platform linux -- Python 3.8.20, pytest-6.2.2, py-1.11.0, pluggy-1.0.0.dev0 -- /workspace/PoC_env/CVE-2024-23334/bin/python
cachedir: .pytest_cache
rootdir: /workspace/aiohttp, configfile: setup.cfg
plugins: cov-2.11.1, mock-3.5.1, asyncio-0.14.0
collecting ... collected 2 items

test_web_urldispatcher.py::test_follow_symlink_directory_traversal[pyloop] PASSED [ 50%]
test_web_urldispatcher.py::test_follow_symlink_directory_traversal_after_normalization[pyloop] FAILED [100%]

=================================== FAILURES ===================================
_____ test_follow_symlink_directory_traversal_after_normalization[pyloop] ______

tmp_path = PosixPath('/tmp/pytest-of-root/pytest-2/test_follow_symlink_directory_1')
aiohttp_client = <function aiohttp_client.<locals>.go at 0x7fb0df1c39d0>

    async def test_follow_symlink_directory_traversal_after_normalization(
        tmp_path: pathlib.Path, aiohttp_client: AiohttpClient
    ) -> None:
        # Tests that follow_symlinks does not allow directory transversal
        # after normalization
        #
        # Directory structure
        # |-- secret_dir
        # |   |-- private_file (should never be accessible)
        # |   |-- symlink_target_dir
        # |       |-- symlink_target_file (should be accessible via the my_symlink symlink)
        # |       |-- sandbox_dir
        # |           |-- my_symlink -> symlink_target_dir
        #
        secret_path = tmp_path / "secret_dir"
        secret_path.mkdir()
    
        # This file is below the symlink target and should not be reachable
        private_file = secret_path / "private_file"
        private_file.write_text("private")
    
        symlink_target_path = secret_path / "symlink_target_dir"
        symlink_target_path.mkdir()
    
        sandbox_path = symlink_target_path / "sandbox_dir"
        sandbox_path.mkdir()
    
        # This file should be reachable via the symlink
        symlink_target_file = symlink_target_path / "symlink_target_file"
        symlink_target_file.write_text("readable")
    
        my_symlink_path = sandbox_path / "my_symlink"
        pathlib.Path(str(my_symlink_path)).symlink_to(str(symlink_target_path), True)
    
        app = web.Application()
    
        # Register global static route:
        app.router.add_static("/", str(sandbox_path), follow_symlinks=True)
        client = await aiohttp_client(app)
    
        await client.start_server()
        # We need to use a raw socket to test this, as the client will normalize
        # the path before sending it to the server.
        reader, writer = await asyncio.open_connection(client.host, client.port)
        writer.write(b"GET /my_symlink/../private_file HTTP/1.1\r\n\r\n")
        response = await reader.readuntil(b"\r\n\r\n")
        assert b"404 Not Found" in response
        writer.close()
        await writer.wait_closed()
    
        reader, writer = await asyncio.open_connection(client.host, client.port)
        writer.write(b"GET /my_symlink/symlink_target_file HTTP/1.1\r\n\r\n")
        response = await reader.readuntil(b"\r\n\r\n")
>       assert b"200 OK" in response
E       AssertionError: assert b'200 OK' in b'HTTP/1.1 404 Not Found\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 14\r\nDate: Thu, 30 Oct 2025 12:30:41 GMT\r\nServer: Python/3.8 aiohttp/4.0.0a2.dev0\r\n\r\n'

aiohttp_client = <function aiohttp_client.<locals>.go at 0x7fb0df1c39d0>
app        = <Application 0x7fb0e422d0f0>
client     = <aiohttp.test_utils.TestClient object at 0x7fb0df758850>
my_symlink_path = PosixPath('/tmp/pytest-of-root/pytest-2/test_follow_symlink_directory_1/secret_dir/symlink_target_dir/sandbox_dir/my_symlink')
private_file = PosixPath('/tmp/pytest-of-root/pytest-2/test_follow_symlink_directory_1/secret_dir/private_file')
reader     = <StreamReader 14 bytes transport=<_SelectorSocketTransport fd=15 read=polling write=<idle, bufsize=0>>>
response   = (b'HTTP/1.1 404 Not Found\r\nContent-Type: text/plain; charset=utf-8\r\nContent'
 b'-Length: 14\r\nDate: Thu, 30 Oct 2025 12:30:41 GMT\r\nServer: Python/3.8 aio'
 b'http/4.0.0a2.dev0\r\n\r\n')
sandbox_path = PosixPath('/tmp/pytest-of-root/pytest-2/test_follow_symlink_directory_1/secret_dir/symlink_target_dir/sandbox_dir')
secret_path = PosixPath('/tmp/pytest-of-root/pytest-2/test_follow_symlink_directory_1/secret_dir')
symlink_target_file = PosixPath('/tmp/pytest-of-root/pytest-2/test_follow_symlink_directory_1/secret_dir/symlink_target_dir/symlink_target_file')
symlink_target_path = PosixPath('/tmp/pytest-of-root/pytest-2/test_follow_symlink_directory_1/secret_dir/symlink_target_dir')
tmp_path   = PosixPath('/tmp/pytest-of-root/pytest-2/test_follow_symlink_directory_1')
writer     = <StreamWriter transport=<_SelectorSocketTransport fd=15 read=polling write=<idle, bufsize=0>> reader=<StreamReader 14 bytes transport=<_SelectorSocketTransport fd=15 read=polling write=<idle, bufsize=0>>>>

test_web_urldispatcher.py:194: AssertionError

---------- coverage: platform linux, python 3.8.20-final-0 -----------
Name                                              Stmts   Miss  Cover
---------------------------------------------------------------------
/workspace/aiohttp/aiohttp/__init__.py               28     11    61%
/workspace/aiohttp/aiohttp/abc.py                    96      7    93%
/workspace/aiohttp/aiohttp/base_protocol.py          66     36    45%
/workspace/aiohttp/aiohttp/client.py                478    318    33%
/workspace/aiohttp/aiohttp/client_exceptions.py     124     52    58%
/workspace/aiohttp/aiohttp/client_proto.py          155    126    19%
/workspace/aiohttp/aiohttp/client_reqrep.py         651    483    26%
/workspace/aiohttp/aiohttp/client_ws.py             215    167    22%
/workspace/aiohttp/aiohttp/compression_utils.py      70     36    49%
/workspace/aiohttp/aiohttp/connector.py             701    516    26%
/workspace/aiohttp/aiohttp/cookiejar.py             252    191    24%
/workspace/aiohttp/aiohttp/formdata.py               94     77    18%
/workspace/aiohttp/aiohttp/hdrs.py                   90      0   100%
/workspace/aiohttp/aiohttp/helpers.py               556    320    42%
/workspace/aiohttp/aiohttp/http.py                    8      0   100%
/workspace/aiohttp/aiohttp/http_exceptions.py        50     20    60%
/workspace/aiohttp/aiohttp/http_parser.py           497    398    20%
/workspace/aiohttp/aiohttp/http_websocket.py        380    286    25%
/workspace/aiohttp/aiohttp/http_writer.py           118     50    58%
/workspace/aiohttp/aiohttp/locks.py                  24     16    33%
/workspace/aiohttp/aiohttp/log.py                     7      0   100%
/workspace/aiohttp/aiohttp/multipart.py             595    487    18%
/workspace/aiohttp/aiohttp/payload.py               225    111    51%
/workspace/aiohttp/aiohttp/pytest_plugin.py         159     61    62%
/workspace/aiohttp/aiohttp/resolver.py               50     31    38%
/workspace/aiohttp/aiohttp/streams.py               392    306    22%
/workspace/aiohttp/aiohttp/tcp_helpers.py            19      2    89%
/workspace/aiohttp/aiohttp/test_utils.py            300    120    60%
/workspace/aiohttp/aiohttp/tracing.py               197     74    62%
/workspace/aiohttp/aiohttp/typedefs.py               30      6    80%
/workspace/aiohttp/aiohttp/web.py                   137     97    29%
/workspace/aiohttp/aiohttp/web_app.py               261     97    63%
/workspace/aiohttp/aiohttp/web_exceptions.py        214     33    85%
/workspace/aiohttp/aiohttp/web_fileresponse.py      146    121    17%
/workspace/aiohttp/aiohttp/web_log.py               102     37    64%
/workspace/aiohttp/aiohttp/web_middlewares.py        56     39    30%
/workspace/aiohttp/aiohttp/web_protocol.py          354    132    63%
/workspace/aiohttp/aiohttp/web_request.py           453    263    42%
/workspace/aiohttp/aiohttp/web_response.py          442    207    53%
/workspace/aiohttp/aiohttp/web_routedef.py          110     49    55%
/workspace/aiohttp/aiohttp/web_runner.py            223     72    68%
/workspace/aiohttp/aiohttp/web_server.py             43      6    86%
/workspace/aiohttp/aiohttp/web_urldispatcher.py     718    357    50%
/workspace/aiohttp/aiohttp/web_ws.py                332    266    20%
/workspace/aiohttp/aiohttp/worker.py                123    123     0%
---------------------------------------------------------------------
TOTAL                                             10341   6207    40%

============================= slowest 10 durations =============================
0.01s teardown tests/test_web_urldispatcher.py::test_follow_symlink_directory_traversal[pyloop]
0.01s teardown tests/test_web_urldispatcher.py::test_follow_symlink_directory_traversal_after_normalization[pyloop]
0.00s setup    tests/test_web_urldispatcher.py::test_follow_symlink_directory_traversal[pyloop]
0.00s call     tests/test_web_urldispatcher.py::test_follow_symlink_directory_traversal_after_normalization[pyloop]
0.00s call     tests/test_web_urldispatcher.py::test_follow_symlink_directory_traversal[pyloop]
0.00s setup    tests/test_web_urldispatcher.py::test_follow_symlink_directory_traversal_after_normalization[pyloop]
=========================== short test summary info ============================
FAILED test_web_urldispatcher.py::test_follow_symlink_directory_traversal_after_normalization[pyloop]
========================= 1 failed, 1 passed in 0.88s ==========================

------------------------------ Standard Error ------------------------------
Coverage.py warning: Module tests/ was never imported. (module-not-imported)

------------------------------ Finish Evaluation ------------------------------


[UnitTest RESULT]: None
[UnitTest MSG]:
 None

[Validation TYPE]: validation_fail